### ISSUE TITLE
Missing chord names after conversion to mac format

### ISSUE THREAD

**Issue by tooh** [0x0L/rocksmith#4]
Found your utility and was happy to have a working solution for conversion on my macos Catalina.

After conversion the chord names are missing.

File is playing OK otherwise

**Comment by 0x0L** [comment]
Hi @tooh 
Could you share the file you're trying to convert ?

**Comment by tooh** [comment]
Will this link work for you ?
http://customsforge.com/page/customsforge_rs_2014_cdlc.html/_/pc-enabled-rs-2014-cdlc/wicked-game-r18697

**Comment by 0x0L** [comment]
Strange. It works for me. Could you unpack both _m and _p and compare the sng files and their json dumps ?

```shell
pyrocksmith --convert wicked_p.psarc
pyrocksmith --unpack wicked_p.psarc
pyrocksmith --unpack wicked_m.psarc
pyrocksmith --print-sng wicked_p/songs/bin/generic/stonesourwickedgame_lead.sng > wicked_p.json
pyrocksmith --print-sng wicked_m/songs/bin/macos/stonesourwickedgame_lead.sng > wicked_m.json
diff wicked_m.json wicked_p.json 
```

**Comment by tooh** [comment]
@0x0L executed these steps 
diff wicked_m.json wicked_p.json gives no differences.

Noticed that there was another version of this song available and used your script on it.
Results include chords.

Thx for now. No further investigation needed .
