### ISSUE TITLE
Converting some files from PC -> MAC causes zlip decompress to throw an erro

### ISSUE THREAD

**Issue by avichaishapira1** [0x0L/rocksmith#8]
`Unexpected error: Traceback (most recent call last): File "rocksmithconvert/services.py", line 55, in run File "rocksmithconvert/services.py", line 69, in process File "rocksmithconvert/services.py", line 118, in convert File "construct/core.py", line 300, in parse_stream File "construct/core.py", line 312, in _parsereport File "rocksmith/psarc.py", line 136, in _parse File "rocksmith/crypto.py", line 74, in decrypt_psarc File "rocksmith/crypto.py", line 52, in decrypt_sng zlib.error: Error -5 while decompressing data: incomplete or truncated stream`

example - writing on the wall by Iron Maiden: [link](https://drive.google.com/file/d/1yCVq0v2SEQP-uHi2_C4EohbjhIho5BG9/view )

**Comment by 0x0L** [comment]
I don't see any issue with your file on the current master branch.

**Comment by avichaishapira1** [comment]
odd, i will re check

**Comment by avichaishapira1** [comment]
ok, you can close this PR, you are correct I built it again with the master branch version and it worked.
